"""Generates media/logo.svg: an infinity sign with the nine classic WoW class colours
flowing around it, on a plain dark round badge.

SVG can't run a gradient along a curve, so the loop is drawn as many short
segments, each blended between neighbouring class colours.

Usage: python media/make_logo.py
"""
import math
import os

SIZE = 400
CENTER = SIZE / 2
STEPS = 720
HALF_WIDTH = 150   # half the width of the infinity sign
STROKE = 38

# Classic class colours, in an order where neighbours blend smoothly; the loop
# ends back at the first colour.
CLASS_COLOURS = [
    ("Warrior", "#c69b6d"),
    ("Druid", "#ff7c0a"),
    ("Rogue", "#fff468"),
    ("Priest", "#ffffff"),
    ("Hunter", "#aad372"),
    ("Mage", "#3fc7eb"),
    ("Shaman", "#0070dd"),
    ("Warlock", "#8788ee"),
    ("Paladin", "#f48cba"),
]


def rgb(hex_colour):
    return tuple(int(hex_colour[i:i + 2], 16) for i in (1, 3, 5))


def blend(t):
    """Colour at position t (0..1) around the loop."""
    colours = [rgb(c) for _, c in CLASS_COLOURS]
    n = len(colours)
    pos = (t % 1) * n
    i = int(pos)
    f = pos - i
    a, b = colours[i], colours[(i + 1) % n]
    return "#%02x%02x%02x" % tuple(round(a[k] + (b[k] - a[k]) * f) for k in range(3))


def point(t):
    """Lemniscate of Bernoulli: a smooth infinity sign."""
    s = 2 * math.pi * t
    d = 1 + math.sin(s) ** 2
    x = HALF_WIDTH * math.cos(s) / d
    y = HALF_WIDTH * math.sin(s) * math.cos(s) / d
    return CENTER + x, CENTER + y


def main():
    segments = []
    for i in range(STEPS):
        t0, t1 = i / STEPS, (i + 1.5) / STEPS  # slight overlap hides seams
        (x0, y0), (x1, y1) = point(t0), point(t1)
        segments.append(
            f'<line x1="{x0:.2f}" y1="{y0:.2f}" x2="{x1:.2f}" y2="{y1:.2f}" stroke="{blend(t0)}"/>'
        )
    # Drawing order alone makes one strand pass cleanly over the other in the middle.

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}" width="{SIZE}" height="{SIZE}">
  <!-- Alts Forever logo, generated by media/make_logo.py: an infinity sign in the
       nine classic class colours on a dark badge. -->
  <circle cx="{CENTER}" cy="{CENTER}" r="{CENTER - 4}" fill="#16213f"/>
  <circle cx="{CENTER}" cy="{CENTER}" r="{CENTER - 4}" fill="none" stroke="#0b1122" stroke-width="8"/>
  <g stroke-width="{STROKE + 10}" stroke-linecap="round" stroke="#0b1122">
    {"".join(s.replace(f'stroke="#', 'data-c="#') for s in segments)}
  </g>
  <g stroke-width="{STROKE}" stroke-linecap="round">
    {"".join(segments)}
  </g>
</svg>
'''
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "logo.svg")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(svg)
    print("wrote", out)


if __name__ == "__main__":
    main()
